import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import "./globals.css";

import { cn } from "@/lib/utils";
import EdgeOverlay from "@/components/ui/EdgeOverlay";

import { StateProvider } from "./provider/StateProvider";
import Nav from "@/components/Nav/Nav";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-sans antialiased", fontSans.variable)}>
        <StateProvider>
          <Nav />

          <div
            vaul-drawer-wrapper=""
            className="flex min-h-screen justify-center bg-white"
          >
            {/* <EdgeOverlay top={true} /> */}
            {children}
            {/* <EdgeOverlay top={false} /> */}
          </div>
        </StateProvider>
      </body>
    </html>
  );
}
